import json
import os
import argparse

def generate_tree_function(tree, tree_id):
    left = tree['left_children']
    right = tree['right_children']
    splits = tree['split_conditions']
    indices = tree['split_indices']
    weights = tree['base_weights']
    
    lines = []
    lines.append(f"    private def tree_{tree_id}(f: Array[Float]): Float =")
    
    def traverse(node_idx, indent):
        ind = "    " * indent
        if left[node_idx] == -1:
            lines.append(f"{ind}{weights[node_idx]}f")
        else:
            split_idx = indices[node_idx]
            split_val = splits[node_idx]
            lines.append(f"{ind}if f({split_idx}) < {split_val}f then")
            traverse(left[node_idx], indent + 1)
            lines.append(f"{ind}else")
            traverse(right[node_idx], indent + 1)
            
    traverse(0, 2)
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--json_model', required=True, help="Path to XGBoost JSON model")
    parser.add_argument('--output', required=True, help="Path to output Scala file")
    args = parser.parse_args()
    
    with open(args.json_model, 'r') as f:
        model = json.load(f)
        
    try:
        base_score = float(model['learner']['learner_model_param']['base_score'])
    except ValueError:
        # Newer versions of xgboost use a vector of scores rather than a single float
        # but we do get a single float here, except that is serialized into a string
        # representing a JSON array, so we parse it again to obtain the actual value.
        vector_value = model['learner']['learner_model_param']['base_score']
        base_score = float(json.loads(vector_value)[0])

    trees = model['learner']['gradient_booster']['model']['trees']
    
    out_lines = [
        "package maf.cli.runnables",
        "",
        "// AUTO-GENERATED BY transpile_xgboost.py"
    ]
    
    CHUNK_SIZE = 100
    num_chunks = (len(trees) + CHUNK_SIZE - 1) // CHUNK_SIZE
    
    for chunk_idx in range(num_chunks):
        out_lines.append(f"object TranspiledOracle_{chunk_idx}:")
        start_idx = chunk_idx * CHUNK_SIZE
        end_idx = min(start_idx + CHUNK_SIZE, len(trees))
        
        out_lines.append(f"    def scoreChunk(features: Array[Float]): Float =")
        out_lines.append(f"        var sum = 0.0f")
        for i in range(start_idx, end_idx):
            out_lines.append(f"        sum += tree_{i}(features)")
        out_lines.append("        sum\n")
        
        for i in range(start_idx, end_idx):
            out_lines.append(generate_tree_function(trees[i], i))
            out_lines.append("")
            
    out_lines.append("object TranspiledOracle:")
    out_lines.append(f"    val baseScore: Float = {base_score}f")
    out_lines.append("    def score(features: Array[Float]): Float =")
    out_lines.append("        var sum = baseScore")
    for chunk_idx in range(num_chunks):
        out_lines.append(f"        sum += TranspiledOracle_{chunk_idx}.scoreChunk(features)")
    out_lines.append("        sum")
    out_lines.append("")
        
    with open(args.output, 'w') as f:
        f.write("\n".join(out_lines))
        
    print(f"Successfully transpiled {len(trees)} trees to {args.output}")

if __name__ == "__main__":
    main()
