import json
import argparse
import textwrap

FEATURE_SNIPPETS = {
    "step": "step.toFloat",
    "wl_size": "wlSize.toFloat",
    "name_hash": "comp.toString.hashCode.toFloat",
    "pending_updates": """
        triggeringProducers.get(comp) match {
            case Some(s) => s.size.toFloat
            case None => 0.0f
        }""",
    "wait": "(step - enqueuedStep.getOrElse(comp, step)).toFloat",
    "size": "getComponentSize(comp).toFloat",
    "out_degree": "outEdges(comp).size.toFloat",
    "in_degree": "inEdges(comp).size.toFloat",
    "was_selected": "if lastSelected.contains(comp) then 1.0f else 0.0f",
    "arrival_index": "arrivalTime.getOrElse(comp, 0L).toFloat",
    "visits": "visitCounts(comp).toFloat",
    "age": "(step - discoveryStep.getOrElse(comp, step)).toFloat",
    "delta_change": "deltaChange.getOrElse(comp, 0.0).toFloat",
    "avg_input_levelToTop": """
        val count = inputLevelCount(comp)
        if count == 0 then 0.0f else inputLevelSum(comp) / count.toFloat""",
    "is_main": """
        if comp == maf.modular.scheme.modf.SchemeModFComponent.Main then 1.0f else 0.0f""",
    "arity": """
        comp match {
            case c: maf.modular.scheme.modf.SchemeModFComponent.Call[_] => c.lambda.args.size.toFloat
            case _ => 0.0f
        }""",
    "avg_neighbor_conv": """
        val neighbors = inEdges.getOrElse(comp, Set.empty)
        if neighbors.isEmpty then 0.0f else {
            var sum = 0.0f
            val it = neighbors.iterator
            while it.hasNext do {
                sum += producerConvergence.getOrElse(it.next(), 0.0f)
            }
            sum / neighbors.size.toFloat
        }""",
    "pending_producers_ratio": """
        val outE = outEdges.getOrElse(comp, Set.empty)
        if outE.isEmpty then 0.0f else {
            var c = 0
            val it = outE.iterator
            while it.hasNext do { if inWorklist.contains(it.next()) then c += 1 }
            c.toFloat / outE.size.toFloat
        }""",
    "pending_consumers_ratio": """
        val inE = inEdges.getOrElse(comp, Set.empty)
        if inE.isEmpty then 0.0f else {
            var c = 0
            val it = inE.iterator
            while it.hasNext do { if inWorklist.contains(it.next()) then c += 1 }
            c.toFloat / inE.size.toFloat
        }""",
    "is_frontier": "if visitCounts(comp) == 0 then 1.0f else 0.0f",
    "progress_ratio": "if step + wlSize == 0 then 0.0f else step.toFloat / (step + wlSize).toFloat"
}

def generate_assignment(index, snippet):
    snippet = textwrap.dedent(snippet).strip()
    lines = snippet.split('\n')
    if len(lines) == 1:
        return f"        arr({index}) = {lines[0]}"
    
    out = f"        arr({index}) = {{\n"
    for line in lines:
        out += f"            {line}\n"
    out += "        }"
    return out

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--json_features', required=True, help="Path to JSON file containing used features")
    parser.add_argument('--output', required=True, help="Path to output Scala trait")
    args = parser.parse_args()

    with open(args.json_features, 'r') as f:
        used_features = json.load(f)

    # Extract base features by stripping 'norm_' and 'log_' prefixes
    base_features = set()
    for f in used_features:
        if f.startswith('norm_'):
            base_features.add(f[5:])
        elif f.startswith('log_'):
            base_features.add(f[4:])
        else:
            base_features.add(f)

    # Always ensure mandatory metadata features are included for the data generation pipeline
    required_aux = {"step", "wl_size", "name_hash", "arrival_index"}
    for f in required_aux:
        base_features.add(f)

    # Sort base features to ensure deterministic code generation
    sorted_base = sorted([f for f in base_features if f in FEATURE_SNIPPETS])
    
    names_array = ", ".join(f'"{f}"' for f in sorted_base)
    
    lines = [
        "package maf.cli.runnables",
        "",
        "import maf.modular.scheme.modf.SchemeModFComponent",
        "",
        "// AUTO-GENERATED BY transpile_features.py",
        "trait TranspiledFeatureExtractor { self: LatticeFeatureBuilder =>",
        "",
        f"    override def featureNames: Array[String] = Array({names_array})",
        "",
        "    override def extractFeatures(comp: SchemeModFComponent, step: Int, wlSize: Int): Array[Float] = {",
        f"        val arr = new Array[Float]({len(sorted_base)})"
    ]

    for i, f in enumerate(sorted_base):
        lines.append(generate_assignment(i, FEATURE_SNIPPETS[f]))

    lines.append("        arr")
    lines.append("    }")
    lines.append("}")

    with open(args.output, 'w') as f:
        f.write("\n".join(lines))

    print(f"Successfully transpiled feature extractor for {len(sorted_base)} base features to {args.output}")

if __name__ == "__main__":
    main()
